apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: "nginx"
    name: ss-ingress
    namespace: {{ $.Release.Namespace }}
spec:
    rules:
        - host: whoogle.stefangenov.site
          http:
              paths:
                  - pathType: Prefix
                    path: /
                    backend:
                        service:
                            name: whoogle
                            port:
                                number: 5000
    tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
        - hosts:
              - stefangenov.site
              - whoogle.stefangenov.site
          secretName: whoogle-cert-224mv